### PR TITLE
Bug fix and updates

### PR DESCRIPTION
**Pull request by marinlauber**
This pull request fixes a bug in the distance function computation for a `NurbsCurve.`  This fixes issue #6 and #7.

The issue was that the bounding box was never set correctly, but luckily, every point on the grid was measured every time, so the distance was still accurate. However, this was slow. Now, the bounding box is computed and set correctly, and it is used to compute the distance function with a discretized step that serves as initial conditions to 2 Newton steps. Otherwise (if the point is not in the bounding box), the value is set to the distance to the middle of the `NurbsCurve`. 

There is now an interpolation routine to get a `BSplineCurve` from a set of points. This only works for B-Spline and not NURBS, as the algorithm is much more complex for NURBS.

There is now force routine to get pressure and viscous forces on the `NurbsCurve` that is better than the one previously implemented.

I also tidied the examples and moved them each to their own file.

I also incorporated the extension format.

Finally, I expanded the tests a bit.

### CODE REVIEW

**Review by weymouth — CHANGES_REQUESTED** [review]
This is very extensive! The only obvious issue I see is that "Manifest" files are supposed to be generated from the Project file, so you should get rid of that.

**Comment by marinlauber** [comment]
I just added the pressure and viscous forces subroutine. I had to re-arrange the structure of the code and add a lot of new functions.
I have added file checks that the correct function is called depending on the body is a `ParamatricBody` or `DynamicBody` and if it represents an `Open` or `Clodes` parametric curve.

**Comment by weymouth** [comment]
I just fixed the conflicts and merged with base. I'll take a look at the code now. It should be fairly easy to get `∮nds(::Parametricbody)` running.

**Comment by marinlauber** [comment]
I have added some more changes; for example, in the `NurbsLocator`, I use the control points to get the bounding box; there is a theorem that states that the control point net is a convex hull of the curve itself.

I fixed the errors in the tests as well.

**Comment by marinlauber** [comment]
There is one annoying conflict with the new forces routines where it calls for `WaterLily.interp` which doesn't exist in the new release. Maybe we should add this asap in yet another release of  `WaterLily`.

**Review by weymouth — APPROVED** [review]

**Comment by weymouth** [comment]
Hoe do we feel about the state of this repo? If the package is ready,  we could register it...

**Comment by marinlauber** [comment]
I have another pull request coming soon for spanwise periodic geometries, after that I think we can register it.

**Pull request merged**
